### PR TITLE
Runtime error locations

### PR DESCRIPTION
**Pull request by arjunguha**
Before:

before

After:

after

Thoughts, @joydeep-b ?

### CODE REVIEW

**Comment by joydeep-b** [comment]
Can we add indentation to the stack print, to indicate that they are all just one error, and not 5 different errors?

**Comment by arjunguha** [comment]
The console is too clever. It only displays the first line of a multi-line string and the user has to click the down-arrow to see the rest:

image

**Comment by joydeep-b** [comment]
Nice. Ready to merge?

**Comment by arjunguha** [comment]
I have not pushed

**Comment by arjunguha** [comment]
OK, this is what is shown:

image

User can click the arrow to see the rest of the trace

**Comment by arjunguha** [comment]
Actually, the UI stuff is in Ocelot, so this is ready to merge.

**Pull request merged**
